[versions]
spring-boot = "4.1.1"
spring-dependency-management = "1.1.7"
kotlin = "2.4.10"
spotless = "8.10.0"
detekt = "1.23.7"
jjwt = "0.13.0"
turbine = "1.2.1"
truth = "1.4.4"
coroutines = "1.10.2"
mockito = "5.23.0"
mockk = "1.14.11"
flapdoodle-embed-mongo = "4.20.1"
springdoc = "3.0.3"
firebase-admin = "9.10.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }

[libraries]
# Reactive MongoDB
spring-boot-starter-data-mongodb-reactive = { module = "org.springframework.boot:spring-boot-starter-data-mongodb-reactive" }

# HATEOAS
spring-boot-starter-hateoas = { module = "org.springframework.boot:spring-boot-starter-hateoas" }

# Reactive web
spring-boot-starter-webflux = { module = "org.springframework.boot:spring-boot-starter-webflux" }

# Validation
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }

# Security
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }

# Documentation
springdoc-openapi-webflux-ui = { module = "org.springdoc:springdoc-openapi-starter-webflux-ui", version.ref = "springdoc" }

# Testing
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-boot-starter-webflux-test = { module = "org.springframework.boot:spring-boot-starter-webflux-test" }
spring-security-test = { module = "org.springframework.security:spring-security-test" }
spring-boot-starter-data-mongodb-test = { module = "org.springframework.boot:spring-boot-starter-data-mongodb-test" }

turbine-test = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
truth = { module = "com.google.truth:truth", version.ref = "truth" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }
reactor-test = { module = "io.projectreactor:reactor-test" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# Development
spring-boot-devtools = { module = "org.springframework.boot:spring-boot-devtools" }

# Jackson
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }

# Kotlin
reactor-kotlin = { module = "io.projectreactor.kotlin:reactor-kotlin-extensions" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-reactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "coroutines" }

# JWT
jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "jjwt" }
jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "jjwt" }
jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "jjwt" }

# Mongo
flapdoodle-mongo = { module = "de.flapdoodle.embed:de.flapdoodle.embed.mongo", version.ref = "flapdoodle-embed-mongo" }
firebase-admin = { module = "com.google.firebase:firebase-admin", version.ref = "firebase-admin" }

# Detekt
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }