spring.application.name=GymPlannerService
spring.mongodb.uri=${MONGO_URI}
spring.mongodb.database=${MONGO_DATABASE_NAME}
gymplanner.app.jwtExpirationMs=${JWT_EXPIRY}
gymplanner.app.jwtSecret=${JWT_SECRET_KEY}
spring.main.web-application-type=reactive
logging.level.root=INFO
logging.level.com.ianarbuckle.gymplannerservice=ERROR
cors.allowed-origins=http://localhost:8080,http://localhost:8081
spring.profiles.active=dev

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html